//Try Catch is used to catch a error that could potentially crash your program

fun main(args:Array<String>){
    //By Eric Ashford
    println("======================================Program Start=====================================")

    try {
        print("Enter a number: ")
        var num2: Double = readLine()!!.toDouble()
        var div = 100 / num2
        println("DIV: $div")
    } catch(ex: Exception){
        println(ex.message)
    }



    println("======================================Program End========================================")
}



/*
========================================================================================================================
======================================================Results===========================================================
========================================================================================================================

Enter a number: 2
DIV: 50.0

Enter a number: 0
/ by zero

Enter a number: a
For input string: "a"

========================================================================================================================
====================================================Results End=========================================================
========================================================================================================================

 */